### PR TITLE
Update upload_picture.py

### PR DESCRIPTION
**Pull request by ortusk**

### CODE REVIEW

**Comment by marcoschwartz** [comment]
I think this is an error, there are your own credentials in the file

**Comment by ortusk** [comment]
Sorry about that! I'm trying to get my arduino project to work, but I seem
to be unable to upload my temboo and dropbox credentials onto my arduino
whenever I update.

**Comment by Kowus** [comment]
Hi Marco, Will the code work for UNO? i cant seem to get my image encoding right.

**Comment by marcoschwartz** [comment]
Hello! No, this is only for the Yun as Python is needed

**Comment by Kowus** [comment]
Thanks. I'm I'm a beginner I'm the maker world... I just got go5a new computer to code with.. Been a while.. do you have any idea how to do it for the UNO?

**Pull request closed without merging**
